//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContainer : DbContext
    {
        public DBContainer()
            : base("name=DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Promotor> Promotor { get; set; }
        public DbSet<Processo> Processo { get; set; }
        public DbSet<EstadoProcesso> EstadoProcesso { get; set; }
        public DbSet<TipoDocumento> TipoDocumento { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<Projeto> ProjetoSet { get; set; }
        public DbSet<TipoProjeto> TipoProjeto { get; set; }
        public DbSet<ProjetoAtribuicao> ProjetoAtribuicao { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<Parecer> ParecerSet { get; set; }
        public DbSet<Especialista> EspecialistaSet { get; set; }
    }
}
