//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBContainer : DbContext
    {
        public DBContainer()
            : base("name=DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Promotor> Promotor { get; set; }
        public DbSet<Processo> Processo { get; set; }
        public DbSet<EstadoProcesso> EstadoProcesso { get; set; }
        public DbSet<TipoDocumento> TipoDocumento { get; set; }
        public DbSet<Documento> Documento { get; set; }
        public DbSet<Projeto> ProjetoSet { get; set; }
        public DbSet<TipoProjeto> TipoProjeto { get; set; }
        public DbSet<ProjetoAtribuicao> ProjetoAtribuicao { get; set; }
        public DbSet<Funcionario> Funcionario { get; set; }
        public DbSet<Parecer> ParecerSet { get; set; }
        public DbSet<Especialista> EspecialistaSet { get; set; }
    }
}
