//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime DataEntrega { get; set; }
        public int TipoDocumentoId { get; set; }
        public int ProjetoId { get; set; }
        public int ParecerNumero { get; set; }
    
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual Projeto Projeto { get; set; }
        public virtual Parecer Parecer { get; set; }
    }
}
