//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialista
    {
        public int TipoProjetoId { get; set; }
        public int FuncionarioNumero { get; set; }
    
        public virtual TipoProjeto TipoProjeto { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
