//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoProcesso
    {
        public EstadoProcesso()
        {
            this.Processo = new HashSet<Processo>();
        }
    
        public int Id { get; set; }
        public string DescricaoEstado { get; set; }
    
        public virtual ICollection<Processo> Processo { get; set; }
    }
}
