//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoProcesso
    {
        public EstadoProcesso()
        {
            this.Processo = new HashSet<Processo>();
        }
    
        public int Id { get; set; }
        public string DescricaoEstado { get; set; }
    
        public virtual ICollection<Processo> Processo { get; set; }
    }
}
