//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Parecer = new HashSet<Parecer>();
            this.ProjetoAtribuicao = new HashSet<ProjetoAtribuicao>();
            this.Especialista = new HashSet<Especialista>();
        }
    
        public int Numero { get; set; }
        public string Nome { get; set; }
        public string Extencao { get; set; }
    
        public virtual ICollection<Parecer> Parecer { get; set; }
        public virtual ICollection<ProjetoAtribuicao> ProjetoAtribuicao { get; set; }
        public virtual ICollection<Especialista> Especialista { get; set; }
    }
}
