//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public Funcionario()
        {
            this.Parecer = new HashSet<Parecer>();
            this.ProjetoAtribuicao = new HashSet<ProjetoAtribuicao>();
            this.Especialista = new HashSet<Especialista>();
        }
    
        public int Numero { get; set; }
        public string Nome { get; set; }
        public string Extencao { get; set; }
    
        public virtual ICollection<Parecer> Parecer { get; set; }
        public virtual ICollection<ProjetoAtribuicao> ProjetoAtribuicao { get; set; }
        public virtual ICollection<Especialista> Especialista { get; set; }
    }
}
