//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parecer
    {
        public Parecer()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int Numero { get; set; }
        public string TextoParecer { get; set; }
        public string DataParecer { get; set; }
        public int FuncionarioNumero { get; set; }
        public int ProjetoId { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Projeto Projeto { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
