//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parecer
    {
        public Parecer()
        {
            this.Documento = new HashSet<Documento>();
        }
    
        public int Numero { get; set; }
        public string TextoParecer { get; set; }
        public string DataParecer { get; set; }
        public int FuncionarioNumero { get; set; }
        public int ProjetoId { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
        public virtual Projeto Projeto { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
    }
}
