//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processo
    {
        public Processo()
        {
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int Id { get; set; }
        public string DataInicio { get; set; }
        public int PromotorNIF { get; set; }
        public int EstadoProcessoId { get; set; }
    
        public virtual Promotor Promotor { get; set; }
        public virtual EstadoProcesso EstadoProcesso { get; set; }
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
