//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processo
    {
        public Processo()
        {
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int Id { get; set; }
        public string DataInicio { get; set; }
        public int PromotorNIF { get; set; }
        public int EstadoProcessoId { get; set; }
    
        public virtual Promotor Promotor { get; set; }
        public virtual EstadoProcesso EstadoProcesso { get; set; }
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
