//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.Documento = new HashSet<Documento>();
            this.Parecer = new HashSet<Parecer>();
            this.ProjetoAtribuicao = new HashSet<ProjetoAtribuicao>();
        }
    
        public int Id { get; set; }
        public string EstadoProjeto { get; set; }
        public System.DateTime DataEntrega { get; set; }
        public System.DateTime DataAprovação { get; set; }
        public int ProcessoId { get; set; }
        public int TipoProjetoId { get; set; }
    
        public virtual Processo Processo { get; set; }
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual TipoProjeto TipoProjeto { get; set; }
        public virtual ICollection<Parecer> Parecer { get; set; }
        public virtual ICollection<ProjetoAtribuicao> ProjetoAtribuicao { get; set; }
    }
}
