//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotor
    {
        public Promotor()
        {
            this.Processo = new HashSet<Processo>();
        }
    
        public int NIF { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Telemovel { get; set; }
        public string Email { get; set; }
        public string CodigoAcesso { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Processo> Processo { get; set; }
    }
}
