//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotor
    {
        public Promotor()
        {
            this.Processo = new HashSet<Processo>();
        }
    
        public int NIF { get; set; }
        public string Nome { get; set; }
        public string Morada { get; set; }
        public string Telemovel { get; set; }
        public string Email { get; set; }
        public string CodigoAcesso { get; set; }
        public string Senha { get; set; }
    
        public virtual ICollection<Processo> Processo { get; set; }
    }
}
