//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProjeto
    {
        public TipoProjeto()
        {
            this.TipoProcessoBase = new HashSet<TipoProjeto>();
            this.Projeto = new HashSet<Projeto>();
            this.Especialista = new HashSet<Especialista>();
        }
    
        public int Id { get; set; }
        public string NrDiasAprovacao { get; set; }
        public string Designacao { get; set; }
        public Nullable<int> TipoProcessoAscendenteId { get; set; }
    
        public virtual ICollection<TipoProjeto> TipoProcessoBase { get; set; }
        public virtual TipoProjeto TipoProcessoAscendente { get; set; }
        public virtual ICollection<Projeto> Projeto { get; set; }
        public virtual ICollection<Especialista> Especialista { get; set; }
    }
}
