//------------------------------------------------------------------------------
// <auto-generated>
//    Este código foi gerado a partir de um modelo.
//
//    Alterações manuais a este ficheiro poderão provocar um comportamento inesperado da sua aplicação.
//    Alterações manuais a este ficheiro serão substituídas se o código for regenerado.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProjeto
    {
        public TipoProjeto()
        {
            this.TipoProcessoBase = new HashSet<TipoProjeto>();
            this.Projeto = new HashSet<Projeto>();
            this.Especialista = new HashSet<Especialista>();
        }
    
        public int Id { get; set; }
        public string NrDiasAprovacao { get; set; }
        public string Designacao { get; set; }
        public Nullable<int> TipoProcessoAscendenteId { get; set; }
    
        public virtual ICollection<TipoProjeto> TipoProcessoBase { get; set; }
        public virtual TipoProjeto TipoProcessoAscendente { get; set; }
        public virtual ICollection<Projeto> Projeto { get; set; }
        public virtual ICollection<Especialista> Especialista { get; set; }
    }
}
